### ISSUE TITLE
1.0.0 Roadmap

### ISSUE THREAD

**Issue by rtfeldman** [rtfeldman/elm-css#10]
- [x] Specify enough docs and exposed modules to satisfy `elm package publish`
- [x] Finish all the combinator permutations (e.g. `>.` and `|#`)
- [x] Add support for pseudo-classes and pseudo-elements
- [x] Run elm-format :boom: 
- [x] Merge in the `npm` branch
- [x] Implement Mixins
- [x] Have the Node .css file generator spit out error messages (and nonzero exit code) if prettyPrint fails
- [x] Split out [elm-css-helpers](https://github.com/rtfeldman/elm-css-helpers) into its own package
- [ ] Split out elm-css-util into its own package, to be shared with elm-css-helpers
- [ ] Implement `@media` with proper error handling
- [ ] Implement `@charset` with proper error handling
- [ ] Add all the [missing keywords](https://github.com/rtfeldman/elm-css/labels/missing%20keywords) :scream_cat: 
- [ ] Add all the missing [elements](https://developer.mozilla.org/en-US/docs/Web/HTML/Element)
- [ ] Figure out a solution for `:not` - don't want to shadow `Basics.not` and also want to be able to express `:not(div, .Foo)` in a type-checked way - could make a series of `not` operators like `&:!$`, but that's not the prettiest
- [ ] Add examples to documentation
- [ ] Resolve all the TODOs
- [ ] Write a basic tutorial explaining things like what `with` does

**Comment by lukewestby** [comment]
Question about elements: should every element be implemented or just some subset? For example, it's possible to style a `<script>` or `<track>` tag but idk why you would want to. I've started going through the list on MDN but I don't want to overdo it. Thoughts?

**Comment by rtfeldman** [comment]
Just a subset, although I'd err on the side of adding more. :)

**Comment by rtfeldman** [comment]
Welp, guess I can close this one.
